name: Generate Snake

on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Create Output Directory
      - name: Create Output Directory
        run: mkdir -p dist

      # Step 3: Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: shiinahan  # Ganti dengan nama pengguna GitHub yang benar
          outputs: dist/github-contribution-grid-snake.svg

      # Step 4: Show Git Status
      - name: Show Git Status
        run: git status

      # Step 5: Push Changes to Output Branch
      - name: Push Changes to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
